### ISSUE TITLE
训练很慢

### ISSUE THREAD

**Issue by samson-wang** [zuokai/roialign#2]
你好，使用ROIAlign之后训练速度很慢，比ROIPooling慢好几倍。不知道是不是符合预期。

**Comment by samson-wang** [comment]
是机器资源的问题。目前看速度没问题。
谢谢！

**Comment by loackerc** [comment]
@samson-wang 不好意思问一下,你把ROIPooling改成ROIAlign之后训练速度是否为ROIPooling的一倍?

cc @zuokai, 我改过来之后速度是ROIPooling的一倍,这个在你的实验是一样的吗?想确定一下我这边的ROIAlign是否安装正确.
